"""Fixed urls created_at and visits visited at

Revision ID: 29f01bf287d3
Revises: 8adaad8906ba
Create Date: 2026-09-08 21:20:29.987115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f01bf287d3'
down_revision: Union[str, Sequence[str], None] = '8adaad8906ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
                'urls',
                'created_at',
                existing_type=postgresql.TIMESTAMP(),
                nullable=False,
                server_default=sa.text('CURRENT_DATE')
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
