"""added visits.visited_at column

Revision ID: 3c5bff694dc3
Revises: 1e3f1d043a7d
Create Date: 2026-09-02 17:50:50.246095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5bff694dc3'
down_revision: Union[str, Sequence[str], None] = '1e3f1d043a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('visited_at', sa.DateTime(), server_default=sa.func.now(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'visited_at')
    # ### end Alembic commands ###
