"""added expires_at and title fields to url

Revision ID: 50b554f5d721
Revises: 58c85a3ce2ba
Create Date: 2026-09-29 19:38:49.010696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b554f5d721'
down_revision: Union[str, Sequence[str], None] = '58c85a3ce2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('title', sa.String(length=30), nullable=True))
    op.add_column('urls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_urls_expires_at'), 'urls', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_expires_at'), table_name='urls')
    op.drop_column('urls', 'expires_at')
    op.drop_column('urls', 'title')
    # ### end Alembic commands ###
