"""fixed urls.created_at

Revision ID: 58c85a3ce2ba
Revises: 89e12f2372a2
Create Date: 2026-09-25 21:32:08.628410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '58c85a3ce2ba'
down_revision: Union[str, Sequence[str], None] = '89e12f2372a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
                'urls',
                'created_at',
                existing_type=postgresql.TIMESTAMP(),
                nullable=False,
                server_default=sa.text('now()')
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
