"""Added is_active columns to user and url; replaced timestamps to current date

Revision ID: 8adaad8906ba
Revises: d7da4747643b
Create Date: 2026-09-08 21:00:33.242927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adaad8906ba'
down_revision: Union[str, Sequence[str], None] = 'd7da4747643b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
